# Generated by Django 4.2.20 on 2025-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_set_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Team Member", "Team Member"),
                ],
                default="Team Member",
                max_length=20,
            ),
        ),
    ]
