# Generated by Django 4.2.20 on 2025-05-06 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crm_app", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="has_set_password",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Team Member", "Team Member"),
                ],
                db_index=True,
                default="Team Member",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "created_at"], name="crm_app_pas_user_id_4dca06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["token", "is_used"], name="crm_app_pas_token_f34631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expires_at", "is_used"], name="crm_app_pas_expires_66adb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active"], name="crm_app_use_email_0d1c49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="crm_app_use_role_20dfcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="crm_app_use_date_jo_635ada_idx"
            ),
        ),
    ]
